"""Script to write the fixed qwen3/block.py for transformers 5.x."""
import os

SITE = '/root/beam-petals-venv/lib/python3.11/site-packages'

block_src = (
    'from typing import Optional, Tuple\n'
    'import torch\n'
    'from transformers.cache_utils import DynamicCache\n'
    '\n'
    'try:\n'
    '    from transformers.models.qwen3.modeling_qwen3 import Qwen3DecoderLayer as _DecoderLayer\n'
    '    from transformers.models.qwen3.modeling_qwen3 import Qwen3RotaryEmbedding as _RotaryEmb\n'
    'except ImportError:\n'
    '    _DecoderLayer = None\n'
    '    _RotaryEmb = None\n'
    '\n'
    'if _DecoderLayer is not None:\n'
    '    class WrappedQwen3Block(_DecoderLayer):\n'
    '        def __init__(self, config, layer_idx=0):\n'
    '            super().__init__(config, layer_idx)\n'
    '            # Ensure attn_implementation is set (Qwen3Config may leave it None)\n'
    '            self._attn_implementation = getattr(config, "_attn_implementation", "eager") or "eager"\n'
    '            if not getattr(config, "_attn_implementation", None):\n'
    '                config._attn_implementation = "eager"\n'
    '            self.layer_idx = layer_idx\n'
    '            self._beam_rope = _RotaryEmb(config=config) if _RotaryEmb is not None else None\n'
    '\n'
    '        def forward(self, hidden_states, *args, attention_mask=None, layer_past=None, use_cache=False, **kwargs):\n'
    '            bs, sl, _ = hidden_states.shape\n'
    '            pkvl = 0\n'
    '            sl_wp = sl\n'
    '\n'
    '            # Always create a fresh DynamicCache; populate with past KV when available\n'
    '            pkv = DynamicCache()\n'
    '            if layer_past is not None:\n'
    '                # beam format: k=(bs*nkv, hd, pkvl), v=(bs*nkv, pkvl, hd)\n'
    '                pkvl = layer_past[0].shape[2]\n'
    '                sl_wp = sl + pkvl\n'
    '                k_m, v_m = self._rcfb(layer_past, bs, pkvl)\n'
    '                pkv.update(k_m, v_m, layer_idx=self.layer_idx)\n'
    '\n'
    '            pos_ids = torch.arange(pkvl, sl + pkvl, dtype=torch.long, device=hidden_states.device).unsqueeze(0)\n'
    '            if "position_embeddings" not in kwargs and self._beam_rope is not None:\n'
    '                kwargs["position_embeddings"] = self._beam_rope(hidden_states, pos_ids)\n'
    '\n'
    '            # transformers>=5.x: past_key_values (plural), DynamicCache updated in-place,\n'
    '            # returns tuple (hidden_states, [opt: attn_weights]) -- no past_key_values in output\n'
    '            outputs = super().forward(\n'
    '                hidden_states,\n'
    '                attention_mask=attention_mask,\n'
    '                position_ids=pos_ids,\n'
    '                past_key_values=pkv,\n'
    '                use_cache=use_cache,\n'
    '                **kwargs\n'
    '            )\n'
    '            h = outputs[0]  # hidden_states is always first element\n'
    '\n'
    '            if use_cache:\n'
    '                # DynamicCache updated in-place; access via key_cache/value_cache lists\n'
    '                k_out = pkv.key_cache[self.layer_idx]    # (bs, nkv, sl_wp, hd)\n'
    '                v_out = pkv.value_cache[self.layer_idx]  # (bs, nkv, sl_wp, hd)\n'
    '                beam_kv = self._rctb((k_out, v_out), bs, sl_wp)\n'
    '                return (h, beam_kv)\n'
    '            return (h,)\n'
    '\n'
    '        def _rcfb(self, kv, bs, sl):\n'
    '            # beam format -> model format: k (bs*nkv, hd, sl) -> (bs, nkv, sl, hd)\n'
    '            k, v = kv\n'
    '            nkv = k.shape[0] // bs   # derived from tensor shape (avoids missing attr)\n'
    '            hd = k.shape[1]\n'
    '            k = k.permute(0, 2, 1).view(bs, nkv, sl, hd)\n'
    '            v = v.view(bs, nkv, sl, hd)\n'
    '            return k, v\n'
    '\n'
    '        def _rctb(self, kv, bs, sl):\n'
    '            # model format (bs, nkv, sl, hd) -> beam format\n'
    '            k, v = kv\n'
    '            nkv = k.shape[1]   # derived from tensor shape\n'
    '            hd = k.shape[3]\n'
    '            k = k.view(bs * nkv, sl, hd).permute(0, 2, 1)\n'
    '            v = v.view(bs * nkv, sl, hd)\n'
    '            return k, v\n'
    '\n'
    'else:\n'
    '    class WrappedQwen3Block:\n'
    '        def __init__(self, *a, **kw):\n'
    '            raise ImportError("Qwen3 requires a newer transformers version")\n'
)

path = os.path.join(SITE, 'petals/models/qwen3/block.py')
with open(path, 'w') as f:
    f.write(block_src)
print(f'Written {len(block_src)} bytes to {path}')
